Repository Galaxia5987/robot-2025, pull requests merged in 2025-01, with the labels that each got.

#68 Fix getAppliedVoltage
  src/main/kotlin/frc/robot/lib/motors/TalonFXSim.java
Labels: bug

#67 Measure extension functions
  src/main/kotlin/frc/robot/lib/ExtensionFunctions.kt
Labels: enhancement

#74 Add geometry classes factories with default values
  src/main/kotlin/frc/robot/lib/ExtensionFunctions.kt
  src/main/kotlin/frc/robot/lib/GeometryFactories.kt
Labels: enhancement

#56 Gripper Subsystem & IO
  src/main/kotlin/frc/robot/subsystems/gripper/Gripper.kt
  src/main/kotlin/frc/robot/subsystems/gripper/GripperConstants.kt
  src/main/kotlin/frc/robot/subsystems/gripper/GripperIO.kt
  src/main/kotlin/frc/robot/subsystems/gripper/GripperIOReal.kt
  src/main/kotlin/frc/robot/subsystems/gripper/GripperIOSim.kt
  src/main/kotlin/frc/robot/subsystems/gripper/GripperPorts.kt
Labels: subsystem

#79 Update measure conversion extension functions
  src/main/kotlin/frc/robot/lib/ExtensionFunctions.kt
Labels: enhancement

#81 TalonFXSim with measures
  src/main/kotlin/frc/robot/lib/motors/TalonFXSim.java
  src/main/kotlin/frc/robot/lib/units/Units.java
  src/main/kotlin/frc/robot/subsystems/elevator/ElevatorIOSim.kt
  src/main/kotlin/frc/robot/subsystems/gripper/GripperIOSim.kt
  src/main/kotlin/frc/robot/subsystems/intake/roller/RollerIOSim.kt
  src/main/kotlin/frc/robot/subsystems/wrist/WristIOSim.kt
Labels: enhancement

#70 Extender IO sim
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderConstants.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderIOSim.kt
Labels: subsystem

#71 Extender IO real
  src/main/kotlin/frc/robot/subsystems/intake/extender/Extender.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderConstants.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderIOReal.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderPorts.kt
Labels: subsystem

#62 Extender subsystem and IO
  src/main/kotlin/frc/robot/subsystems/intake/extender/Extender.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderConstants.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderIO.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderIOReal.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderIOSim.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderPorts.kt
Labels: subsystem

#90 Climber IO sim
  src/main/kotlin/frc/robot/subsystems/climber/ClimberConstants.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberIOSim.kt
Labels: subsystem

#72 climber subsystem-io
  .gitignore
  src/main/kotlin/frc/robot/subsystems/AUTO-SPEC.md
  src/main/kotlin/frc/robot/subsystems/climber/Climber.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberConstants.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberIO.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberIOReal.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberIOSim.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberPorts.kt
Labels: subsystem

#96 Initialize subsystems
  src/main/kotlin/frc/robot/Initializer.kt
  src/main/kotlin/frc/robot/RobotContainer.kt
Labels: enhancement

#102 Intake commands
  src/main/kotlin/frc/robot/subsystems/intake/IntakeCommands.kt
  src/main/kotlin/frc/robot/subsystems/intake/roller/RollerConstants.kt
Labels: enhancement

#124 Add soft limits
  src/main/kotlin/frc/robot/subsystems/climber/ClimberConstants.kt
  src/main/kotlin/frc/robot/subsystems/elevator/Elevator.kt
  src/main/kotlin/frc/robot/subsystems/elevator/ElevatorIO.kt
  src/main/kotlin/frc/robot/subsystems/elevator/ElevatorIOReal.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/Extender.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderConstants.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderIO.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderIOReal.kt
  src/main/kotlin/frc/robot/subsystems/wrist/WristConstants.kt
  src/main/kotlin/frc/robot/subsystems/wrist/WristIOReal.kt
Labels: enhancement

#122 Intake safety feature
  src/main/kotlin/frc/robot/subsystems/intake/extender/Extender.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderConstants.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderIOReal.kt
Labels: enhancement, subsystem

#144 Add `with*` extension functions for `Pose3d`
  src/main/kotlin/frc/robot/lib/GeomExtensionFunctions.kt
Labels: enhancement
