Repository Galaxia5987/robot-2025, pull requests merged in 2025-02, with the labels that each got.

#150 Add Maple Sim
  src/main/kotlin/frc/robot/Initializer.kt
  src/main/kotlin/frc/robot/Robot.kt
  src/main/kotlin/frc/robot/RobotContainer.kt
  src/main/kotlin/frc/robot/lib/PhoenixUtil.java
  src/main/kotlin/frc/robot/subsystems/ReefCommands.kt
  src/main/kotlin/frc/robot/subsystems/Visualizer.kt
  src/main/kotlin/frc/robot/subsystems/drive/Drive.java
  src/main/kotlin/frc/robot/subsystems/drive/GyroIOSim.java
  src/main/kotlin/frc/robot/subsystems/drive/ModuleIOSim.java
  src/main/kotlin/frc/robot/subsystems/elevator/Elevator.kt
  src/main/kotlin/frc/robot/subsystems/elevator/ElevatorConstants.kt
  src/main/kotlin/frc/robot/subsystems/intake/roller/RollerConstants.kt
  src/main/kotlin/frc/robot/subsystems/intake/roller/RollerIOSim.kt
  src/main/kotlin/frc/robot/subsystems/wrist/WristConstants.kt
  vendordeps/maple-sim.json
Labels: enhancement

#130 Add SysID
  src/main/kotlin/frc/robot/lib/ExtensionFunctions.kt
  src/main/kotlin/frc/robot/subsystems/climber/Climber.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberIO.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberIOReal.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberIOSim.kt
  src/main/kotlin/frc/robot/subsystems/elevator/Elevator.kt
  src/main/kotlin/frc/robot/subsystems/elevator/ElevatorIO.kt
  src/main/kotlin/frc/robot/subsystems/elevator/ElevatorIOReal.kt
  src/main/kotlin/frc/robot/subsystems/elevator/ElevatorIOSim.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/Extender.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderIO.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderIOReal.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderIOSim.kt
  src/main/kotlin/frc/robot/subsystems/wrist/Wrist.kt
  src/main/kotlin/frc/robot/subsystems/wrist/WristIO.kt
  src/main/kotlin/frc/robot/subsystems/wrist/WristIOReal.kt
  src/main/kotlin/frc/robot/subsystems/wrist/WristIOSim.kt
Labels: enhancement

#155 Calibrate Elevator
  src/main/kotlin/frc/robot/subsystems/elevator/Elevator.kt
  src/main/kotlin/frc/robot/subsystems/elevator/ElevatorConstants.kt
  src/main/kotlin/frc/robot/subsystems/elevator/ElevatorIOReal.kt
  src/main/kotlin/frc/robot/subsystems/elevator/ElevatorIOSim.kt
  src/main/kotlin/frc/robot/subsystems/elevator/ElevatorPorts.kt
Labels: Calibration

#159 Wrist calibrations
  src/main/kotlin/frc/robot/subsystems/wrist/Wrist.kt
  src/main/kotlin/frc/robot/subsystems/wrist/WristConstants.kt
  src/main/kotlin/frc/robot/subsystems/wrist/WristIOReal.kt
  src/main/kotlin/frc/robot/subsystems/wrist/WristPorts.kt
Labels: Calibration

#164 Calibrate reefmaster
  src/main/kotlin/frc/robot/RobotContainer.kt
  src/main/kotlin/frc/robot/subsystems/ReefCommands.kt
  src/main/kotlin/frc/robot/subsystems/elevator/Elevator.kt
  src/main/kotlin/frc/robot/subsystems/elevator/ElevatorConstants.kt
  src/main/kotlin/frc/robot/subsystems/gripper/Gripper.kt
  src/main/kotlin/frc/robot/subsystems/gripper/GripperConstants.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/Extender.kt
  src/main/kotlin/frc/robot/subsystems/intake/extender/ExtenderConstants.kt
  src/main/kotlin/frc/robot/subsystems/wrist/Wrist.kt
  src/main/kotlin/frc/robot/subsystems/wrist/WristConstants.kt
  src/main/kotlin/frc/robot/subsystems/wrist/WristIOReal.kt
Labels: Calibration

#167 New climb
  src/main/kotlin/frc/robot/subsystems/climber/Climber.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberConstants.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberIO.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberIOReal.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberIOSim.kt
  src/main/kotlin/frc/robot/subsystems/climber/ClimberPorts.kt
  src/main/kotlin/frc/robot/subsystems/gripper/GripperConstants.kt
Labels: subsystem

#108 Led subsystem
  src/main/kotlin/frc/robot/Initializer.kt
  src/main/kotlin/frc/robot/subsystems/leds/LEDs.kt
  src/main/kotlin/frc/robot/subsystems/leds/LEDsConstants.kt
Labels: subsystem
